import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        h-main-screen flex flex-col justify-center items-center
        `}
      >

      <header>
        <h1>A minha App Next!</h1>
        <nav>
          <ul>
            <li><Link href="/">Intro</Link></li>
            <li><Link href="/">Rota</Link></li>
            <li><Link href="/">Sobre</Link></li>
          </ul>
        </nav>
      </header>

      <main>
        {children}  
      </main>

      <footer>
        DIW
      </footer>

      </body>
    </html>
  );
}
